name: Testing and deployment #Название workflow

on:
  push:
      branches: [master] #Запускаем при push на ветке master

jobs:
  testing:
    runs-on: ubuntu-latest #Запускаем на последней версии ubuntu
    env: #Прописываем все переменные, которые создали в секретах на github
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
    services: #Перечисляем все сревисы
      postgresql_main: 
        image: postgres:latest #Образ для постгреса
        env: #Переменные окружения для постгреса обязательно указываем
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports: #Список портов 
          - 5432:5432 
        options: #Проверки перед запуском (проверяет 5 раз с интервалом в 5 секунд запустился ли постгрес)
          --health-cmd pg_isready 
          --health-interval 5s 
          --health-timeout 5s
          --health-retries 5
    steps: #Шаги проверок
      - name: Проверяем на наличие изменений
        uses: actions/checkout@v4 #Проверяет наличие изменений в репозитории, uses - используем готовое решение 

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: pip install -r requirements.txt #run - пишем сами, что нужно сделать

      - name: Линтинг
        run: flake8 logistic/ --exclude=logistic/migrations #Проверяем папку logistic/ исключаем папку с миграциями 

      - name: Тестирование
        run: pytest
        env: 
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: ${{ env.DEBUG }}
          DB_ENGINE: ${{ env.DB_ENGINE }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}

      - name: Деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          password: ${{ secrets.SSH_PASSWORD}}
          script: expect /home/anna/stocks_products/deploy.exp

        
